config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'gallery/index'
  resources :stores
  get 'home/index'
  root 'home#index'
  devise_for :users
  get 'admin/login'
  post 'admin/login'
  get 'admin/logout'
  get 'gallery/checkout'
  post 'gallery/checkout'
  get 'gallery/purchase'
  get 'gallery/search'
  post 'gallery/search'
end

app/models/store.rb
class Store < ApplicationRecord
    has_many_attached :files
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]
  before_action :admin_logged_in?

  def index
    @stores = Store.all
  end

 
  def show
  end
  
  def new
    @store = Store.new
  end

  def edit
  end
  
  def create
    @store = Store.new(store_params)
    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url(@store), notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to store_url(@store), notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_store
      @store = Store.find(params[:id])
    end
  
    def store_params
      params.require(:store).permit(:name, :category, :description, :price, :author, files: [])
    end
  
    def admin_logged_in?
      if session[:admin].nil?
        flash[:notice] = "You need to do admin login to continue!"
        redirect_to admin_login_url
      end
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<section  style="background-color: lightgray;">
<%= form_with(model: store) do |f| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <h3 class="mb-5">New Store</h3>

            <div class="form-outline mb-4">
              <div class="field">
                <%= f.label :name, class: "form-label" %><br />
                <%= f.text_field :name, autofocus: true, class: "form-control form-control-lg" %>
              </div>
            </div>

            <div class="form-outline mb-4">
              <div class="field">
                <%= f.label :description, class: "form-label" %><br />
                <%= f.text_area :description, autofocus: true, class: "form-control form-control-lg" %>
              </div>
            </div>

            <div class="form-outline mb-4">
                <div class="field">
                    <%= f.label :price, class: "form-label" %><br />
                    <%= f.number_field :price, class: "form-control form-control-lg" %>
                </div>
            </div>


            <div class="form-outline mb-4">
                <div class="field">
                    <%= f.label :author, class: "form-label" %><br />
                    <%= f.text_field :author, class: "form-control form-control-lg" %>
                </div>
            </div>

            <div class="form-outline mb-4">
                <div class="field">
                    <%= f.label :category, class: "form-label" %><br />
                    <%= f.text_field :category, class: "form-control form-control-lg" %>
                </div>
            </div>


            <div class="field">
              <%= f.label :files %>
              <%= f.file_field :files, multiple: true %>
            </div>

            <!-- Checkbox -->
            <div class="actions">
              <%= f.submit "Submit",class: "btn btn-secondary btn-lg btn-block"  %>
            </div>

            <hr class="my-4">
              <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/stores/edit.html.erb
<%= render 'form', store: @store %>
<div style="text-align:center">
    <%= link_to 'Show', @store, class:"btn btn-secondary", style:"color: white; text-align:center;" %> |
    <%= link_to 'Back', stores_path,class:"btn btn-secondary", style:"color: white; text-align:center;"%>
</div>

app/views/stores/index.html.erb
<div class="container vh-300" >
    <h1 style="text-align:center;color:grey;">
	Stores
    </h1>
    <p id="notice"><%= notice %></p>
    <table class="table table-bordered">
		<thead>
			<tr>
				<th scope="col">Name</th>
				<th scope="col">Category</th>
				<th scope="col">Color</th>
				<th scope="col">Price</th>
				<th scope="col">Description</th>
			</tr>
		</thead>
		<tbody>
		  <% @stores.each do |store| %>
		    <tr>
		      <td><%= store.name %></td>
		      <td><%= store.category %></td>
		      <td><%= store.author %></td>
		      <td><%= store.description %></td>
		      <td><%= store.price %></td>
		      <td><%= link_to 'Show', store, class:"btn btn-secondary btn-sm btn-block;", style: "color: white" %></td>
		      <td><%= link_to 'Edit', edit_store_path(store), class:"btn btn-secondary btn-sm btn-block;", style: "color: white"%></td>
		      <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-secondary btn-sm btn-block;", style: "color: white" %></td>
		    </tr>
		  <% end %>
		</tbody>
    </table>
    <%= link_to 'New Store', new_store_path, class:"btn btn-secondary btn-sm btn-block;", style: "color: white; align: center"%>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js">
    </script>
  </div>

app/views/stores/new.html.erb
<%= render 'form', store: @store %>
<%= link_to 'Back', stores_path ,class:"btn btn-secondary", style:"color: white; text-align:center;"%>

app/views/stores/show.html.erb
<div class="flex-container", style="display:flex; padding:15%">
<div>
<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>
<p>
  <strong>Category:</strong>
  <%= @store.category %>
</p>
<p>
  <strong>Description:</strong>
  <%= @store.description %>
</p>
<p>
  <strong>Price:</strong>
  <%= @store.price %>
</p>
<p>
  <strong>Author:</strong>
  <%= @store.author %>
</p>
<%= link_to 'Edit', edit_store_path(@store),class:"btn btn-secondary", style:"color: white; text-align:center;" %> |
<%= link_to 'Back', stores_path,class:"btn btn-secondary", style:"color: white; text-align:center;"%>
</div>
<div>
<% @store.files.each do |file| %>
  <%= image_tag file, width:"250px" %><br>
<% end %>
</div>
</div>