config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'gallery/index'
  resources :stores
  get 'home/index'
  root 'home#index'
  devise_for :users
  get 'admin/login'
  post 'admin/login'
  get 'admin/logout'
  get 'gallery/checkout'
  post 'gallery/checkout'
  get 'gallery/purchase'
  get 'gallery/search'
  post 'gallery/search'
end

app/models/cart.rb
class Cart < ApplicationRecord
has_many :line_items, :dependent => :destroy

def add_product(store_id)
	current_item = line_items.find_by_store_id(store_id)
	if current_item
		current_item.quantity += 1
	else
		current_item = line_items.build(:store_id => store_id)
	end
	current_item
end

def total_price
	line_items.to_a.sum { |item| item.total_price }
end 
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[  edit update destroy ]

  def index
    @carts = Cart.all
  end

  def show
    begin
      @cart = Cart.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to @cart, :notice => 'Invalid Cart'
      else
        respond_to do |format|
          format.html 
          format.json { render json: @cart }
      end
    end
  end

  def new
    @cart = Cart.new
  end

  def edit
  end


  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
	</script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js">
	</script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js">
	</script>
<br/>
<br/>
	<div class="container vh-100">
		<h1 style="text-align:center;color:grey;">
			<% unless cart.line_items.empty? %>
            Your Cart
		</h1>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th scope="col">Quantity</th>
					<th scope="col">Name</th>
					<th scope="col">Price</th>
				</tr>
			</thead>
			<tbody>
                <%= render(cart.line_items) %>
                <tr>
                <td colspan="2">Total</td>
                <td class="total_cell"><%= number_to_currency(cart.total_price)  %></td>
	            </tr>
			</tbody>
		</table>
        <% session[:amount] = cart.total_price %>
        <%= button_to 'Empty Cart', cart, :method => :delete, :confirm => 'Are you sure?', class: "btn btn-secondary btn-sm btn-block;"%>
    
    <br/>
		<%= link_to "Continue Shopping",:controller=>"gallery",:action=>"index" %> | 
		<% if user_signed_in? %>
		<%= link_to "Checkout", gallery_checkout_path, class:"link-secondary" %>
		<% else %>
		<%= link_to "login", new_user_session_path, class:"link-secondary" %>
		<% end %>
    	<% end %>
	</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>
      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>
<%= render 'form', cart: @cart %>
<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Carts</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>
<%= render 'form', cart: @cart %>
<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render @cart %>